### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by dopc** [CristianViorelPopa/BART-TL-topic-label-generation#1]
Hey, congratulations for your publication and thanks for sharing your code!

I have tried running the code, and got below error in the first step.

`Traceback (most recent call last):
  File "lda/apply_lda.py", line 12, in <module>
    from model_to_simple_csv import save_topic_words_simple_csv
ModuleNotFoundError: No module named 'model_to_simple_csv'` 

Any suggestion for a solution?

**Comment by CristianViorelPopa** [comment]
Thanks for bringing this to my attention! Some files were missing, I fixed the issue in the last commit, can you try again now?

**Comment by dopc** [comment]
Thanks for your quick reply! It is solved.
