### ISSUE TITLE
Fine-tuned model(s) and how to run the code

### ISSUE THREAD

**Issue by dopc** [CristianViorelPopa/BART-TL-topic-label-generation#2]
Hey,

1. Is it possible you to share your fine-tuned BART models?

and

2. I have tried run the code with following the steps you provide, but after `step 1`, there are only files of sentences of the topics. I could not find the way to run the `step 2` because there is no JSON file and NETL output from `step 1`.
Can you please provide more detailed flow to run the code or just a Jupyter notebook as a demo?

**Comment by dopc** [comment]
@CristianViorelPopa any update?

**Comment by CristianViorelPopa** [comment]
Yes, I'm so sorry for the delay. I'm working on creating a notebook with the end-to-end workflow and re-training the models to upload them to a permanent storage (thinking of huggingface models).

I will comment again when these are ready. Again, sorry for the delay ☹️

**Comment by dopc** [comment]
No problem at all.

Great to hear from the progress which means you care the GitHub issues. Thanks so much 👍

**Comment by CristianViorelPopa** [comment]
@dopc I added a notebook with the whole process: https://github.com/CristianViorelPopa/BART-TL-topic-label-generation/blob/main/notebooks/end_to_end_workflow.ipynb.

You can follow that for now until I push the models to https://huggingface.co/models, which should be by the end of the week. I advise to go the route of Huggingface fine-tuning (you will see what I mean in the notebook). Hope this helps!

**Comment by CristianViorelPopa** [comment]
I uploaded the models on Huggingface as well:
- https://huggingface.co/cristian-popa/bart-tl-all
- https://huggingface.co/cristian-popa/bart-tl-ng

**Comment by dopc** [comment]
That's great! Thanks so much.
